### PR TITLE
Update semicolon rule to correctly parse subqueries in create statements

### LINKED ISSUE #43: Incorrect semicolon-termination detection
Example:

image

Statements of this form say "Statement not terminated with semicolon." even though they are.

### PR DESCRIPTION
**Pull request by nathan-boyd**
- Add test for create view and create function statements
  - Update rule to allow for semicolons following subquery fragments
  - Resolves #43

### CODE REVIEW

**Comment by nathan-boyd** [comment]
This was interesting. I started investigating #43 with the expectation that I would find a bug within our line number calculation within subqueries of create statements, but that is not what I found. It seems that subqueries don't pars such that they are allowed to contain a terminating semicolon. The parser doesn't return an error, the "lastToken" is always the token preceding the statements semicolon. 

Interestingly enough, this seems to be in line with the languages [select statement syntax](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-transact-sql)

To account for the lack of a semicolon in the fragment, I introduced a softening of the semicolon-termination rule. This change allows the rule to be satisfied by the presence of a semicolon as the last token or the token following it.

I am interested in other opinions on this matter. I have considered the fact that the missing semicolon in the [select statement syntax](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-transact-sql) might be an oversight on the part of the TSQL team.

```
<SELECT statement> ::=    
    [ WITH { [ XMLNAMESPACES ,] [ <common_table_expression> [,...n] ] } ]  
    <query_expression>   
    [ ORDER BY { order_by_expression | column_position [ ASC | DESC ] }   
  [ ,...n ] ]   
    [ <FOR Clause>]   
    [ OPTION ( <query_hint> [ ,...n ] ) ]   
<query_expression> ::=   
    { <query_specification> | ( <query_expression> ) }   
    [  { UNION [ ALL ] | EXCEPT | INTERSECT }  
        <query_specification> | ( <query_expression> ) [...n ] ]   
<query_specification> ::=   
SELECT [ ALL | DISTINCT ]   
    [TOP ( expression ) [PERCENT] [ WITH TIES ] ]   
    < select_list >   
    [ INTO new_table ]   
    [ FROM { <table_source> } [ ,...n ] ]   
    [ WHERE <search_condition> ]   
    [ <GROUP BY> ]   
    [ HAVING < search_condition > ]  
```
[create view statement](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-view-transact-sql)
```
-- definition of create or alter view
CREATE [ OR ALTER ] VIEW [ schema_name . ] view_name [ (column [ ,...n ] ) ]   
[ WITH <view_attribute> [ ,...n ] ]   
AS select_statement   
[ WITH CHECK OPTION ]   
[ ; ]  
```

**Comment by geoffbaker** [comment]
I think it is missed - look the examples and they all seem to be there. Also look at the Azure version and its there

**Comment by nathan-boyd** [comment]
@geoffbaker yeah its weird, they must be auto-generating their ANTLR grammar using this same syntax, hence our behavior.

**Comment by nathan-boyd** [comment]
merged in a5c82b7dd2453856689a7453af1612accad44626

**Pull request closed without merging**
