### PR TITLE
Add --fix cmd (only adds 1 rule fix for now, the semicolon.)

### PR DESCRIPTION
**Pull request by stephenweaver**
Once this PR and pattern is agreed on and merged, I'll add a few other auto fix rules.

Most of the files are due to the first couple commits of commonizing rule code into BaseRuleVisitor 

You can see a more relevant diff here
https://github.com/stephenweaver/tsqllint/compare/e3b053a98aa806b555413f82f12270c0d95d473c..3e8e5bb52af1bf327acd9639107b6465f292a2bf

### CODE REVIEW

**Comment by nathan-boyd** [comment]
👁️ 👁️

**Comment by nathan-boyd** [comment]
fixed the build issue and rebase PR

**Comment by nathan-boyd** [comment]
@stephenweaver this is looking good so far, while i'm reviewing would you mind updating the readme with instructions on how to use the new arg, what it does, etc.

**Comment by stephenweaver** [comment]
@nathan-boyd I've also [created this PR](https://github.com/tsqllint/tsqllint-vscode-extension/pull/49) to update the VS code extension to support it.

**Comment by stephenweaver** [comment]
@nathan-boyd Had some time today, so I went ahead and added some more fixable rules.  Let me know if you want me to merge that into this PR or keep it in stages.

https://github.com/stephenweaver/tsqllint/pull/1

**Review by nathan-boyd — APPROVED** [review]
:shipit:

**Pull request merged**
