### PR TITLE
Add set variable rule

### PR DESCRIPTION
**Pull request by nathan-boyd**
- Create new "set variable rule" tests
  - Create new rule
  - Update config generator
  - Update rule parser

### CODE REVIEW

**Comment by nathan-boyd** [comment]
open to other ideas on the rule name maybe "set-variable-style" or something

**Comment by nathan-boyd** [comment]
need to write tests for update

**Comment by dougwilson** [comment]
As for the name, I think "set-variable" makes sense vs "set-variable-style" -- I would say no need to qualify with the "-style". Of course, this rule just as an simple none, warn, error is starting to get border line :) I think once we have parameterized rules, it should really be "set-variable": ["error", "select"] to say that not using select is an error. But that is a thought for a later change, not this one, just wanted to put it out there :)

**Comment by nathan-boyd** [comment]
@dougwilson updated readme, added tests

**Pull request merged**
