### PR TITLE
Multi threading support

### PR DESCRIPTION
**Pull request by willsmith9182**
Add support for processing with multiple threads and command line option to override. Still defaults to 1 when not specified

I'm using this to lint a directory with ish 3000 scripts or more, single threaded this was taking around 2 minutes. Support for multi threading enabled me to get it down to around 30s 

Thoughts?

### CODE REVIEW

**Comment by willsmith9182** [comment]
Obviously tests need adding.

**Comment by nathan-boyd** [comment]
Hi, thanks for the contribution. I'm in favor of multi-threading to improve performance, once this passes the build I'll take a look at the change.

**Comment by willsmith9182** [comment]
Well the build is now passing 💃

**Comment by willsmith9182** [comment]
@nathan-boyd  what am I missing here about codecov/patch check?

**Comment by nathan-boyd** [comment]
```
source/TSQLLint.Console/Application.cs | 97.14% <66.66%> (-2.86%)
```
that file's overall coverage dropped so the coverage check failed. if you dive into the diffs you should be able to see the missing blocks in the report.

**Comment by PiDiBi** [comment]
hey @willsmith9182 performance was improved by PR https://github.com/tsqllint/tsqllint/pull/224 
that PR contains only parallel reading of files and is not touching parsing (parsing is still one thread only)
I did some testes locally for parallel parsing with thousands of files and I believe that underlying MS dll is not ready

**Comment by willsmith9182** [comment]
ooo, that's exciting. might come back to this at some point but fer now i'll close as it's not gonna get improved anytime soon by me :)

**Pull request closed without merging**
