### PR TITLE
Add .NET 7 support

### PR DESCRIPTION
**Pull request by bdovaz**
Add the possibility to run it with .NET 7

We want to upgrade in [MegaLinter](https://github.com/oxsecurity/megalinter) the SDK to .NET 7 but TSQLLint only works with .NET 6.

This PR adds the target to .NET 7 in addition to the existing one (.NET 6).

### CODE REVIEW

**Comment by bdovaz** [comment]
@nathan-boyd fails because the Docker image is only .NET 7 and multitargeting requires also the 6.0 SDK from what I see in the logs.

I have tried to keep compatibility with .NET 6 but I see that some kind of change needs to be made in the circleci file to run with the 2 SDKs installed.

**Comment by bdovaz** [comment]
@nathan-boyd at the moment I have made it run the tests in a specific targetFramework (.net7).

To make it run in the 2 targetFramework there are 2 options:
1. split the "build" and "build and notify" jobs into 2 (per targetFramework).
2. Create a custom .net7 image that includes the .net6 runtime (required for dotnet test step)
    1. https://circleci.com/docs/custom-images/
    2. https://stackoverflow.com/a/71311201/699056

What do you think? I understand that the first option is much simpler.

**Comment by bdovaz** [comment]
@nathan-boyd ping!

**Comment by bdovaz** [comment]
@nathan-boyd ping!

**Review by nathan-boyd — APPROVED** [review]
:shipit:

**Pull request merged**
