### PR TITLE
Update to TargetFramework 8.0 and Enhancements

### PR DESCRIPTION
**Pull request by TommyE123**
Hi @nathan-boyd, 

This PR introduces support for `TargetFramework .net 8.0` to the project and includes several minor improvements and updates.

## Context:

- [.NET and .NET Core Support Policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)
- `.NET 7` is now out of support since May 14, 2024.
- `.NET 6` is scheduled to go out of support on November 12, 2024.
- Updating to `.NET 8` ensures the project remains current, benefiting from new features, performance improvements, and security updates until November 10, 2026.
- `CI/CD` build and deploy pipelines could start to drop support for older versions, necessitating this update for ongoing compatibility and maintenance.

## Changes:

- Updated `.gitignore` to the latest version.
- Updated `TargetFramework` in project files to include `net8.0`.
- Updated `NUnit` from `v3.13.3` to `v3.14.0` (note: version v4+ was avoided due to potential breaking changes in tests).
- Updated `Microsoft.NET.Test.Sdk` from `v17.2.0` to `v17.10.0`.
- Minor solution file update to the latest Visual Studio version.
- Updated `circleci/slack` version from `v4.6.1` to `v4.13.3`.

## Testing:

image

image

## Additional Notes:

- Certain NuGet packages should be updated to their latest versions but were not changed without thorough testing to avoid potential issues.
- The changelog has not been updated in this PR, but please feel free to do so as needed.

## Conclusion:
If there are any concerns or issues, please let me know, and I will address them promptly.
Thank you for reviewing this PR and look forward to your feedback.

Tom

### CODE REVIEW

**Comment by nathan-boyd** [comment]
@TommyE123 thanks for the contribution, ill review this

**Comment by TommyE123** [comment]
Thanks @nathan-boyd for getting back to me regarding this PR. I appreciate your time and input.

I wanted to also mention that TSQLLint is currently disabled in [megalinter](https://github.com/oxsecurity/megalinter), which I'm helping out supporting. One of the goals of this PR is to update TSQLLint to work with .NET 8, incorporating its improvements and new functionality. This would allow us to move towards re-enabling TSQLLint in megalinter, enhancing our SQL linting capabilities with your excellent project.

If you have any suggestions for changes or improvements to the PR to help achieve this, please let me know. I'm open to any feedback you might have.

Thanks again,
Tom

**Review by nathan-boyd — APPROVED** [review]

**Comment by melmendo** [comment]
Thank you for the contribution here @TommyE123! Our team is anxiously awaiting the ability to target .net 8.0.  @nathan-boyd, do you have any time estimates when this merge will be released?

**Comment by nathan-boyd** [comment]
version 1.16.0 has been release to Nuget with the latest changes

**Pull request merged**
